### ISSUE TITLE
Publish for sbt-1.0.0-RC2?

### ISSUE THREAD

**Issue by ngbinh** [scf37/sbt-overwatch#1]
it was released yesterday http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0-RC2

**Comment by scf37** [comment]
sbt-overwatch plugin is hardly useful without integration with sbt-revolver which is not published for sbt 1.0 yet: https://dl.bintray.com/sbt/sbt-plugin-releases/io.spray/sbt-revolver/

How do you want to use it?

**Comment by ngbinh** [comment]
there are tracking issue https://github.com/spray/sbt-revolver/issues/62 and pending pr https://github.com/spray/sbt-revolver/issues/74 so I guess sbt-revolver artifact for sbt 1.0.0 will be available soon.

**Comment by scf37** [comment]
Published for sbt 1.x
